# Form implementation generated from reading ui file 'gradesGui.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentGrades(object):
    def setupUi(self, StudentGrades):
        StudentGrades.setObjectName("StudentGrades")
        StudentGrades.resize(200, 300)
        StudentGrades.setMinimumSize(QtCore.QSize(200, 300))
        StudentGrades.setMaximumSize(QtCore.QSize(200, 300))
        self.centralwidget = QtWidgets.QWidget(parent=StudentGrades)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(6, 0, 191, 20))
        self.titleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.nameLabel.setObjectName("nameLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.scoreLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.scoreLabel.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.scoreLabel.setObjectName("scoreLabel")
        self.scoreLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.scoreLineEdit.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.scoreLineEdit.setObjectName("scoreLineEdit")
        self.submitErrorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.submitErrorLabel.setGeometry(QtCore.QRect(0, 80, 201, 20))
        self.submitErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.submitErrorLabel.setObjectName("submitErrorLabel")
        self.submitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(60, 100, 75, 23))
        self.submitButton.setObjectName("submitButton")
        self.searchGradeLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.searchGradeLabel.setGeometry(QtCore.QRect(6, 130, 191, 20))
        self.searchGradeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchGradeLabel.setObjectName("searchGradeLabel")
        self.searchNameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.searchNameLabel.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.searchNameLabel.setObjectName("searchNameLabel")
        self.searchNameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchNameLineEdit.setGeometry(QtCore.QRect(60, 160, 113, 20))
        self.searchNameLineEdit.setObjectName("searchNameLineEdit")
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.searchButton.setObjectName("searchButton")
        self.searchErrorLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.searchErrorLabel.setGeometry(QtCore.QRect(6, 220, 191, 20))
        self.searchErrorLabel.setText("")
        self.searchErrorLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.searchErrorLabel.setObjectName("searchErrorLabel")
        StudentGrades.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StudentGrades)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        StudentGrades.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StudentGrades)
        self.statusbar.setObjectName("statusbar")
        StudentGrades.setStatusBar(self.statusbar)

        self.retranslateUi(StudentGrades)
        QtCore.QMetaObject.connectSlotsByName(StudentGrades)

    def retranslateUi(self, StudentGrades):
        _translate = QtCore.QCoreApplication.translate
        StudentGrades.setWindowTitle(_translate("StudentGrades", "Student Grades"))
        self.titleLabel.setText(_translate("StudentGrades", "Enter Student\'s Name and Grade"))
        self.nameLabel.setText(_translate("StudentGrades", "Name:"))
        self.scoreLabel.setText(_translate("StudentGrades", "Score:"))
        self.submitErrorLabel.setText(_translate("StudentGrades", "Submit Student\'s Score"))
        self.submitButton.setText(_translate("StudentGrades", "Submit"))
        self.searchGradeLabel.setText(_translate("StudentGrades", "Search Student Grade"))
        self.searchNameLabel.setText(_translate("StudentGrades", "Name: "))
        self.searchButton.setText(_translate("StudentGrades", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentGrades = QtWidgets.QMainWindow()
    ui = Ui_StudentGrades()
    ui.setupUi(StudentGrades)
    StudentGrades.show()
    sys.exit(app.exec())
