# Form implementation generated from reading ui file 'gradesGUI.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentGrades(object):
    def setupUi(self, StudentGrades):
        StudentGrades.setObjectName("StudentGrades")
        StudentGrades.resize(200, 300)
        StudentGrades.setMinimumSize(QtCore.QSize(200, 300))
        StudentGrades.setMaximumSize(QtCore.QSize(200, 300))
        self.centralwidget = QtWidgets.QWidget(parent=StudentGrades)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 0, 191, 20))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 60, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 201, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(6, 130, 191, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 160, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(6, 220, 191, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_7.setObjectName("label_7")
        StudentGrades.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=StudentGrades)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        StudentGrades.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=StudentGrades)
        self.statusbar.setObjectName("statusbar")
        StudentGrades.setStatusBar(self.statusbar)

        self.retranslateUi(StudentGrades)
        QtCore.QMetaObject.connectSlotsByName(StudentGrades)

    def retranslateUi(self, StudentGrades):
        _translate = QtCore.QCoreApplication.translate
        StudentGrades.setWindowTitle(_translate("StudentGrades", "Student Grades"))
        self.label.setText(_translate("StudentGrades", "Enter Student\'s Name and Grade"))
        self.label_2.setText(_translate("StudentGrades", "Name:"))
        self.label_3.setText(_translate("StudentGrades", "Score:"))
        self.label_4.setText(_translate("StudentGrades", "Submit Student\'s Score"))
        self.pushButton.setText(_translate("StudentGrades", "Submit"))
        self.label_5.setText(_translate("StudentGrades", "Search Student Grade"))
        self.label_6.setText(_translate("StudentGrades", "Name: "))
        self.pushButton_2.setText(_translate("StudentGrades", "Search"))
        self.label_7.setText(_translate("StudentGrades", "(Search for names already submitted)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentGrades = QtWidgets.QMainWindow()
    ui = Ui_StudentGrades()
    ui.setupUi(StudentGrades)
    StudentGrades.show()
    sys.exit(app.exec())
